export const GITMOJIS_TYPES = {
  none: {
    emoji: "",
    code: "",
    description: "No gitmoji",
    name: "none",
  },
  sparkles: {
    emoji: "✨",
    code: ":sparkles:",
    description: "Introduce new features.",
    name: "sparkles",
  },
  bug: {
    emoji: "🐛",
    code: ":bug:",
    description: "Fix a bug.",
    name: "bug",
  },
  memo: {
    emoji: "📝",
    code: ":memo:",
    description: "Add or update documentation.",
    name: "memo",
  },
  lipstick: {
    emoji: "💄",
    code: ":lipstick:",
    description: "Add or update the UI and style files.",
    name: "lipstick",
  },
  recycle: {
    emoji: "♻️",
    code: ":recycle:",
    description: "Refactor code.",
    name: "recycle",
  },
  zap: {
    emoji: "⚡️",
    code: ":zap:",
    description: "Improve performance.",
    name: "zap",
  },
  whiteCheckMark: {
    emoji: "✅",
    code: ":white_check_mark:",
    description: "Add, update, or pass tests.",
    name: "white-check-mark",
  },
  buildingConstruction: {
    emoji: "🏗️",
    code: ":building_construction:",
    description: "Make architectural changes.",
    name: "building-construction",
  },
  constructionWorker: {
    emoji: "👷",
    code: ":construction_worker:",
    description: "Add or update CI build system.",
    name: "construction-worker",
  },
  chore: {
    emoji: "🤖",
    code: ":robot:",
    description: "Other changes that don't modify src or test files.",
    name: "robot",
  },
  rewind: {
    emoji: "⏪️",
    code: ":rewind:",
    description: "Revert changes.",
    name: "rewind",
  },
  fire: {
    emoji: "🔥",
    code: ":fire:",
    description: "Remove code or files.",
    name: "fire",
  },
  tada: {
    emoji: "🎉",
    code: ":tada:",
    description: "Begin a project.",
    name: "tada",
  },
  bookmark: {
    emoji: "🔖",
    code: ":bookmark:",
    description: "Release / Version tags.",
    name: "bookmark",
  },
  greenHeart:{
    emoji: "💚",
    code: ":green_heart:",
    description: "Fix CI Build.",
    name: "green-heart",
  },
  arrowDown: {
    emoji: "⬇️",
    code: ":arrow_down:",
    description: "Downgrade dependencies.",
    name: "arrow-down",
  },
  arrowUp: {
    emoji: "⬆️",
    code: ":arrow_up:",
    description: "Upgrade dependencies.",
    name: "arrow-up",
  },
  wrench: {
    emoji: "🔧",
    code: ":wrench:",
    description: "Add or update configuration files.",
    name: "wrench",
  },
  hammer: {
    emoji: "🔨",
    code: ":hammer:",
    description: "Add or update development scripts.",
    name: "hammer",
  },
};